version: "3.3"  # optional since v1.27.0
services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: contract
      PGDATA: /var/lib/postgresql/contract/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgressql:/var/lib/postgresql/data
      - ./config/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - contract-app-network

  customer-service:
    image: com.reza.learning.contract/customer-service:1.0-SNAPSHOT
    container_name: customer-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contract
      - SPRING_DATASOURCE_USERNAME=sc_customer
      - SPRING_DATASOURCE_PASSWORD=123456

    ports:
      - "8081:8080"
    volumes:
      - ./config/service-common/logback-spring.xml:/logback-spring.xml:ro
      - ./runtime/logs/customer-service:/app

    healthcheck:
      test: ["CMD", "curl", "-f", "http://customer-service:8080/actuator/status"]
      interval: 1000s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
    networks:
      - contract-app-network
    restart: on-failure

  order-service:
    image: com.reza.learning.contract/order-service:1.0-SNAPSHOT
    container_name: order-service

    ports:
      - "8082:8080"
    volumes:
      - ./config/service-common/logback-spring.xml:/logback-spring.xml:ro
      - ./runtime/logs/order-service:/app

    environment:
      - APP_INTEGRATION_CUSTOMERSERVICE_ENDPOINT=http://customer-service:8080/
      - APP_INTEGRATION_PRODUCTSERVICE_ENDPOINT=http://product-service:8080/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contract
      - SPRING_DATASOURCE_USERNAME=sc_order
      - SPRING_DATASOURCE_PASSWORD=123456

    healthcheck:
      test: ["CMD", "curl", "-f", "http://order-service:8080/actuator/status"]
      interval: 1000s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
    networks:
      - contract-app-network
    restart: on-failure

  product-service:
    image: com.reza.learning.contract/product-service:1.0-SNAPSHOT
    container_name: product-service

    ports:
      - "8083:8080"
    volumes:
      - ./config/service-common/logback-spring.xml:/logback-spring.xml:ro
      - ./runtime/logs/product-service:/app

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contract
      - SPRING_DATASOURCE_USERNAME=sc_product
      - SPRING_DATASOURCE_PASSWORD=123456

    healthcheck:
      test: ["CMD", "curl", "-f", "http://product-service:8080/actuator/status"]
      interval: 1000s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
    networks:
      - contract-app-network
    restart: on-failure

networks:
  contract-app-network:
    driver: bridge

volumes:
  postgressql:
    external:
      true
