spring:
  application:
    name: customer-service
  aop:
    proxy-target-class: true
  jackson:
    property-naming-strategy: KEBAB_CASE
management :
  endpoints :
    web :
      exposure :
        include : '*'

springdoc:
  enable-kotlin: false



